name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v2

      - name: Flutter 설정
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"

      - name: 의존성 설치
        run: flutter pub get

      - name: 코드 포맷 검사
        run: flutter format --set-exit-if-changed .

      - name: 유닛 테스트 실행
        run: flutter test --coverage

      - name: APK 빌드
        run: flutter build apk --release
